version: '3'

    services:
    api:
        build: .
        ports:
        - "8000:8000"
        volumes:
        - .:/app
        environment:
        - MONGODB_URI=mongodb://mongo:27017/market_research
        depends_on:
        - mongo

    mongo:
        image: mongo:latest
        ports:
        - "27017:27017"
        volumes:
        - mongodb_data:/data/db

    volumes:
    mongodb_data:
    